spring:
  jpa:
    show-sql: true
server:
  servlet:
    session:
      cookie:
        secure: false     # http://localhost en développement
app:
  media:
    dir: ./media
  tmp-dir: ./tmp
logging:
  level:
    fr.sanglierlab.travel: DEBUG
